import { describe, expect, it } from "vitest";

import { buildPdfElement, PDF_CONTENT_WIDTH_PX } from "@/lib/build-print-document";

describe("buildPdfElement", () => {
  it("renders GFM tables and marks wide tables", () => {
    const markdown = [
      "# Report",
      "",
      "| A | B | C | D | E |",
      "|---|---|---|---|---|",
      "| 1 | 2 | 3 | 4 | 5 |",
    ].join("\n");

    const element = buildPdfElement(markdown, "Test report");

    expect(element.style.width).toBe(`${PDF_CONTENT_WIDTH_PX}px`);
    expect(element.querySelector("table")?.classList.contains("pdf-table-wide")).toBe(true);
    expect(element.textContent).toContain("Generated by Research Agent");
  });
});
