import { marked } from "marked";

/** A4 printable width: 210mm − 30mm margins ≈ 680px at 96dpi */
export const PDF_CONTENT_WIDTH_PX = 680;

const PDF_COLORS = {
  background: "#fffcf7",
  foreground: "#1c1917",
  heading: "#b45309",
  subheading: "#44403c",
  body: "#44403c",
  meta: "#78716c",
  border: "#e7e0d5",
  tableHeader: "#fef3c7",
} as const;

function contentStyles(): string {
  return `
    .pdf-content h1 {
      font-size: 22pt;
      font-weight: 700;
      color: ${PDF_COLORS.heading};
      margin: 0 0 8px;
      padding-bottom: 10px;
      border-bottom: 2px solid ${PDF_COLORS.border};
      page-break-inside: avoid;
      break-inside: avoid;
    }
    .pdf-content h2 {
      font-size: 14pt;
      font-weight: 600;
      color: ${PDF_COLORS.foreground};
      margin: 24px 0 10px;
      padding-left: 10px;
      border-left: 3px solid ${PDF_COLORS.heading};
      page-break-inside: avoid;
      break-inside: avoid;
      page-break-after: avoid;
    }
    .pdf-content h3 {
      font-size: 12pt;
      font-weight: 600;
      color: ${PDF_COLORS.subheading};
      margin: 16px 0 8px;
      page-break-inside: avoid;
      break-inside: avoid;
    }
    .pdf-content h4 {
      page-break-inside: avoid;
      break-inside: avoid;
    }
    .pdf-content p {
      margin: 0 0 12px;
      line-height: 1.75;
      page-break-inside: avoid;
      break-inside: avoid;
    }
    .pdf-content ul, .pdf-content ol {
      margin: 0 0 12px;
      padding-left: 24px;
    }
    .pdf-content li {
      margin-bottom: 6px;
      line-height: 1.75;
      page-break-inside: avoid;
      break-inside: avoid;
    }
    .pdf-content hr {
      border: none;
      border-top: 1px solid ${PDF_COLORS.border};
      margin: 20px 0;
    }
    .pdf-table-wrap {
      page-break-inside: avoid;
      break-inside: avoid;
      margin: 16px 0;
    }
    .pdf-content table {
      width: 100%;
      table-layout: fixed;
      border-collapse: collapse;
      font-size: 8pt;
      page-break-inside: avoid;
      break-inside: avoid;
    }
    .pdf-content table.pdf-table-wide {
      font-size: 7pt;
    }
    .pdf-content th, .pdf-content td {
      border: 1px solid ${PDF_COLORS.border};
      padding: 4px 5px;
      text-align: left;
      vertical-align: top;
      word-break: break-word;
      overflow-wrap: anywhere;
    }
    .pdf-content tr {
      page-break-inside: avoid;
      break-inside: avoid;
    }
    .pdf-content thead { background: ${PDF_COLORS.tableHeader}; }
    .pdf-content th { font-weight: 600; }
    .pdf-content strong { font-weight: 600; color: ${PDF_COLORS.foreground}; }
  `;
}

function postProcessTables(content: HTMLElement): void {
  const tables = content.querySelectorAll("table");

  tables.forEach((table) => {
    const firstRow = table.querySelector("tr");
    const columnCount = firstRow?.children.length ?? 0;

    if (columnCount >= 5) {
      table.classList.add("pdf-table-wide");
    }

    const wrap = document.createElement("div");
    wrap.className = "pdf-table-wrap";
    table.parentNode?.insertBefore(wrap, table);
    wrap.appendChild(table);
  });
}

export function buildPdfElement(markdown: string, topic: string): HTMLElement {
  marked.setOptions({ gfm: true, breaks: false });

  const root = document.createElement("div");
  root.className = "pdf-export-root";
  root.style.cssText = `
    background: ${PDF_COLORS.background};
    color: ${PDF_COLORS.body};
    font-family: Georgia, "Times New Roman", serif;
    font-size: 11pt;
    line-height: 1.75;
    padding: 24px;
    width: ${PDF_CONTENT_WIDTH_PX}px;
    box-sizing: border-box;
  `;

  const style = document.createElement("style");
  style.textContent = contentStyles();
  root.appendChild(style);

  const meta = document.createElement("div");
  meta.style.cssText = `
    font-family: Arial, Helvetica, sans-serif;
    font-size: 9pt;
    letter-spacing: 0.08em;
    text-transform: uppercase;
    color: ${PDF_COLORS.meta};
    margin-bottom: 20px;
  `;
  meta.textContent = `${topic} · ${new Date().toLocaleDateString()}`;
  root.appendChild(meta);

  const content = document.createElement("div");
  content.className = "pdf-content";
  content.innerHTML = marked.parse(markdown) as string;
  postProcessTables(content);
  root.appendChild(content);

  const footer = document.createElement("div");
  footer.style.cssText = `
    margin-top: 32px;
    padding-top: 12px;
    border-top: 1px solid ${PDF_COLORS.border};
    font-family: Arial, Helvetica, sans-serif;
    font-size: 9pt;
    color: ${PDF_COLORS.meta};
    font-style: italic;
  `;
  footer.textContent = "Generated by Research Agent";
  root.appendChild(footer);

  return root;
}
