export type { AgentStep, AgentStatus, PipelineStep } from "@/lib/types";

import type { PipelineStep } from "@/lib/types";

export interface MockSession {
  topic: string;
  steps: PipelineStep[];
  report: string;
}

export const IDLE_STEPS: PipelineStep[] = [
  { agent: "supervisor", status: "idle", label: "Supervisor" },
  { agent: "search", status: "idle", label: "Search" },
  { agent: "analysis", status: "idle", label: "Analysis" },
  { agent: "writer", status: "idle", label: "Writer" },
  { agent: "finish", status: "idle", label: "Done" },
];

export const SAMPLE_REPORT = `# AI Agents Market Trends 2026

## Executive Summary

Multi-agent systems have moved from research labs into production across enterprise software, developer tooling, and consumer applications. The market is consolidating around orchestration frameworks, specialized agent roles, and cost-aware routing.

## Key Findings

### 1. Orchestration Frameworks Dominate
LangGraph, CrewAI, and AutoGen lead adoption among teams building production agent workflows. StateGraph patterns with checkpointed memory are becoming the default architecture.

### 2. Cost Control Is Critical
Teams are implementing step budgets, model routing (flash vs. pro), and caching strategies. Average cost per research task dropped 40% year-over-year as models improve.

### 3. Tool-Use Patterns Matured
Search → fetch → analyze loops remain the most common pattern. Agents with structured output and retry logic show significantly higher completion rates.

## Recommendations

- Start with a supervisor + specialist agent pattern
- Implement hard step and cost budgets from day one
- Persist state via checkpointers for session continuity

---

*Generated by Multi-Agent Research System (mock preview)*
`;

export function buildCompletedSession(topic: string): MockSession {
  return {
    topic,
    steps: [
      { agent: "supervisor", status: "done", label: "Supervisor" },
      { agent: "search", status: "done", label: "Search" },
      { agent: "analysis", status: "done", label: "Analysis" },
      { agent: "writer", status: "done", label: "Writer" },
      { agent: "finish", status: "done", label: "Done" },
    ],
    report: SAMPLE_REPORT.replace(
      "AI Agents Market Trends 2026",
      topic.length > 60 ? `${topic.slice(0, 57)}...` : topic,
    ),
  };
}

export function buildRunningSteps(activeIndex: number): PipelineStep[] {
  return IDLE_STEPS.map((step, index) => {
    if (index < activeIndex) {
      return { ...step, status: "done" as const };
    }
    if (index === activeIndex) {
      return { ...step, status: "active" as const };
    }
    return { ...step, status: "idle" as const };
  });
}

export const MOCK_RUN_SEQUENCE = [0, 1, 2, 3, 4, 5] as const;
export const MOCK_STEP_DELAY_MS = 400;
